apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: ztsc-quarkus-hello-service-app-trigger
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: ztsc-quarkus-hello-service-app
  template:
    # In newer trigger versions the 'name' field will be deprecated and is
    # replaced by 'ref' field.
    name: ztsc-quarkus-hello-service-app
