apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: quarkus-hello-service-app
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: quarkus-hello-service-app-trigger
